// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using projectfinal.Controllers.data;

#nullable disable

namespace projectfinal.Migrations
{
    [DbContext(typeof(Applicationdbcontext))]
    [Migration("20260304080836_lastmigrate")]
    partial class lastmigrate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("projectfinal.Controllers.models.Cricketer", b =>
                {
                    b.Property<Guid>("jersey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("jersey");

                    b.ToTable("cricket");
                });
#pragma warning restore 612, 618
        }
    }
}
